### ISSUE TITLE
sequence order in the menus

### ISSUE THREAD

**Issue by jvanheld** [IFB-ElixirFr/PIPprofileR#3]
@thomasdenecker 

Would it be possible to order the sequences by *decreasing* similarity with the reference sequence? Currently they are sorted by increasing similarity (screenshot below), but we are generally interested first by the most similar sequences.

Also, the term "species" should be replaced by "sequence" in the forms, because a sequence does not always correspond to a species (could be strains, or even paralogous sequences belonging to the same genome). 

Thanks

@jvanheld 

![image](https://user-images.githubusercontent.com/10991210/103273621-0caaca00-49c0-11eb-8f6e-d1a960b6135b.png)

**Comment by jvanheld** [comment]
Hi @thomasdenecker 

Just a kind reminder for this request. 
Would it be possible to sort the sequences from the closest to the most distant in the color selection menu ? 

Thanks

@jvanheld

**Comment by thomasdenecker** [comment]
Thank you for the suggestion. It's done in the last commit.
