### ISSUE TITLE
Sequence display checkboxes

### ISSUE THREAD

**Issue by jvanheld** [IFB-ElixirFr/PIPprofileR#8]
Dear @thomasdenecker 

Would it be possible to add an option enabling to enable / disable the display of each sequence on the PIP profiles?
Currently, the "Filter" function enables to select or unselect sequences from the input, but once this is done all the alignments are recomputed, and the figure re-generated, and we lose all the previously specified parameters (e.g. the sequence-specific colors).

In practice it is generally only after having done the alignemnt and generated the first drawing that one sees which sequences might be hidden in order to simplify the graph. This would in principle only refresh the displayed curves on the profile, but there should be no necessity to recompute the whole 1-to-n alignement, and we do not want to re-specify all the colors each time we suppress a curve from the plot. 

Thanks a lot

@jvanheld

**Comment by thomasdenecker** [comment]
Thank you for the suggestion. A tab is now available with the possibility to choose finely the sequences to be displayed. It's done in the last commit ✅
